### ISSUE TITLE
Please make this repo private during the advent period.

### ISSUE THREAD

**Issue by resturp** [D0an/AdventOfCode-2019#2]
<<english version below>>
Beste DOan,

Het lijkt mij niet zo sportief om AOC code te publiceren op Github, zo vroeg in de competitie.
Zou je de repo op private willen zetten?

Vriendelijke groet,
Thomas
============
Dear DOan,

We do AOC in our school as a challenge. I would be grateful if you would make this a private repo during the advent period. Koen is on our private leaderboard and his github account is public.

Kind regards
Thomas Boose

**Comment by D0an** [comment]
Though I would agree with you if I’d release the answers sooner on the day it would be annoying, but since I only release the solutions later on the day the points you get for taking less time should no longer have an impact. 

No player who seriously plays AdventOfCode will ‘cheat’ by stealing my code as they play to solve the puzzles themselves. Therefore I’m deciding to keep my answers public.

**Comment by resturp** [comment]
Respect,

Kind regards.

Thomas Boose
E: thomas@boose.nl
M: 06-28649991



Op wo 4 dec. 2019 om 01:15 schreef D0an <notifications@github.com>:
